# Generated by Django 4.2.2 on 2023-06-22 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habitacionm',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nhabitacion', models.CharField(max_length=100, verbose_name='N habitacion')),
                ('cantidadpas', models.CharField(max_length=100)),
                ('orientacionhab', models.CharField(max_length=100)),
                ('estadohab', models.CharField(max_length=100)),
            ],
        ),
    ]
