# Generated by Django 4.2.2 on 2023-06-22 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoteleria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitacionm',
            name='cantidadpas',
            field=models.IntegerField(verbose_name='Cantidad pasajeros admitidos'),
        ),
        migrations.AlterField(
            model_name='habitacionm',
            name='nhabitacion',
            field=models.IntegerField(verbose_name='N habitacion'),
        ),
    ]
