# Generated by Django 4.2.2 on 2023-06-28 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoteleria', '0002_alter_habitacionm_cantidadpas_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pasajerom',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rpasajero', models.CharField(max_length=50, verbose_name='Rut pasajero')),
                ('nombrepasajero', models.CharField(max_length=50, verbose_name='Nombre completo pasajero')),
                ('pasajeroresponsable', models.IntegerField(verbose_name='Pasajero responsable Si o No')),
                ('nhabitacionpas', models.IntegerField(verbose_name='Número de habitación de pasajero')),
                ('cargo', models.IntegerField(verbose_name='Cargo de habitación por pasajero')),
            ],
        ),
        migrations.AlterField(
            model_name='habitacionm',
            name='estadohab',
            field=models.CharField(max_length=100, verbose_name='Estado habitación'),
        ),
        migrations.AlterField(
            model_name='habitacionm',
            name='nhabitacion',
            field=models.IntegerField(verbose_name='Numero de habitación'),
        ),
        migrations.AlterField(
            model_name='habitacionm',
            name='orientacionhab',
            field=models.CharField(max_length=100, verbose_name='Orientación habitación'),
        ),
    ]
