# Generated by Django 4.2.2 on 2023-06-28 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoteleria', '0003_pasajerom_alter_habitacionm_estadohab_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pasajerom',
            name='pasajeroresponsable',
            field=models.CharField(max_length=2, verbose_name='Pasajero responsable Si o No'),
        ),
    ]
